excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://okayrenee.github.io
title: pretend this is important
tagline: life liberty & the pursuit of a job after college
description: i think i'm hilarious and i hope you think so too.
paginate: 10